run:
  timeout: 5m
  tests: true
  modules-download-mode: readonly

linters:
  enable:
    - gofmt
    - govet
    - errcheck
    - staticcheck
    - unused
    - gosimple
    - ineffassign
    - typecheck

linters-settings:
  govet:
    enable:
      - shadow
    settings:
      shadow:
        strict: false

  errcheck:
    check-type-assertions: true
    check-blank: false

issues:
  exclude-rules:
    # Exclude generated templ files
    - path: _templ\.go$
      linters:
        - all

  max-issues-per-linter: 0
  max-same-issues: 0
